### ISSUE TITLE
Status of posts (pending vs answered)

### ISSUE THREAD

**Issue by 92ammarraza** [CMU-313/fall23-nodebb-qwerty-coders#1]
As a student, I want to be able to see the status of my questions, such as whether they are pending, answered, in the Q&A forum, so that I can see when to open the question answers after I ask.

Students can see the status of questions (pending vs answered) in the Q&A forum. This is useful for students to see which questions are answered if they have similar questions.

**Comment by kellyycha** [comment]
closing this issue because we will not use it
