### ISSUE TITLE
Add indicator for unanswered posts

### ISSUE THREAD

**Issue by kellyycha** [CMU-313/fall23-nodebb-qwerty-coders#18]
User Story: Status of post 

Estimated effort: ~3 hr

Dependencies: none

Acceptance criteria:
* Test by creating a post from student account
* Symbol initially shows up on the post preview since it is unanswered
* Once it is answered, the symbol changes to indicate instructor or student answer

**Comment by kaitlyncliu** [comment]
Already implemented with teasers
